// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import HelloController from "./hello_controller"
import ImageUploadController from "./image_upload_controller";
import FilterFormController from "./filter_form_controller"
import ResetFilterController from "./reset_filter_controller"
import FlashController from "./flash_controller"

application.register("hello", HelloController)
application.register("image-upload", ImageUploadController)
application.register("flash", FlashController)
application.register("filter-form", FilterFormController)
application.register("reset-filter", ResetFilterController)
import "./railsui"
