--- !ruby/object:Railsui::Configuration
application_name: Rails UI
support_email: support@example.com
theme: hound
colors:
  primary:
    '50': "#e6f0fa"
    '100': "#cce1f5"
    '200': "#99c3eb"
    '300': "#66a5e0"
    '400': "#3388d6"
    '500': "#0056a9"
    '600': "#004f98"
    '700': "#004f98"
    '800': "#003a77"
    '900': "#003066"
    '950': "#00234d"
  secondary:
    '50': "#f8fafc"
    '100': "#f1f5f9"
    '200': "#e2e8f0"
    '300': "#cbd5e1"
    '400': "#94a3b8"
    '500': "#64748b"
    '600': "#475569"
    '700': "#334155"
    '800': "#1e293b"
    '900': "#0f172a"
    '950': "#020617"
pages:
- about
- pricing
- dashboard
- projects
- project
- messages
- message
- assignments
- calendar
- people
- profile
- activity
- settings
- notifications
- billing
- team
- integrations
body_classes: antialiased h-full bg-slate-50 dark:bg-slate-900 dark:text-slate-100
  text-slate-800
