--- !ruby/object:Railsui::Configuration
application_name: Rails UI
support_email: support@example.com
theme: hound
colors:
  primary:
    '50': "#e6f0fa"
    '100': "#cce1f5"
    '200': "#99c3eb"
    '300': "#66a5e0"
    '400': "#3388d6"
    '500': "#0056a9"
    '600': "#004f98"
    '700': "#004280"
    '800': "#003a77"
    '900': "#003066"
    '950': "#00234d"
  secondary: 
    '50': "#fff3e0"
    '100': "#ffe0b2"
    '200': "#ffcc80"
    '300': "#ffb74d"
    '400': "#ffa726"
    '500': "#ff8a00"
    '600': "#f57c00"
    '700': "#ef6c00"
    '800': "#e65100"
    '900': "#bf360c"
    '950': "#8f2500"
  gray: 
    '50': "#f9fafb"
    '100': "#f3f4f6"
    '200': "#e5e7eb"
    '300': "#d1d5db"
    '400': "#9ca3af"
    '500': "#6b7280"
    '600': "#4b5563"
    '700': "#374151"
    '800': "#1f2937"
    '900': "#111827"
    '950': "#030712"
  success:
    main: "#1e7e34"
  danger:
    main: "#be123c"
  warning:
    main: "#d39e00"
  info:
    main: "#117a8b"
  light:
    main: "#dae0e5"
  dark:
    main: "#23272b"
  gradient-primary:
    light: "linear-gradient(to bottom, #e6f0fa, #000000)"
    dark: "linear-gradient(to bottom, #00234d, #ffffff)"
  gradient-secondary:
    light: "linear-gradient(to bottom, #fff3e0, #000000)"
    dark: "linear-gradient(to bottom, #ff8a00, #ffffff)"
pages:
- about
- pricing
- dashboard
- projects
- project
- messages
- message
- assignments
- calendar
- people
- profile
- activity
- settings
- notifications
- billing
- team
- integrations
body_classes: antialiased h-full bg-slate-50 dark:bg-slate-900 dark:text-slate-100 text-slate-800
